// <auto-generated />
namespace BattleGame.Cli;

// 此类型由 script/generate_l10n.sh 生成，请修改 assets_dev/l10n.csv 后重新生成。
internal static class GameText
{
    internal const string Title = "AI 命运法庭";
    internal const string Subtitle = "策略 · 随机事件 · 一次申诉";
    internal const string NamePrompt = "请输入玩家名字：";
    internal const string NameEmpty = "名字不能为空，请重新输入。";
    internal const string InputEnded = "输入已结束，游戏退出。";
    internal const string ComputerName = "DeepSeek 对手";
    internal const string DifficultyPrompt = "选择电脑难度（1：简单  2：中等  3：困难）：";
    internal const string FatePrompt = "选择命运模式（1：英雄  2：公平  3：残酷）：";
    internal const string InvalidChoice = "输入无效，请重新选择。";
    internal const string AiOnline = "DeepSeek 已启用：三个角色使用隔离上下文，调用失败时自动回退";
    internal const string AiOffline = "未配置 DEEPSEEK_API_KEY：当前使用本地策略和本地裁判";
    internal const string BattleIntro = "{0} VS {1}";
    internal const string BattleRules = "攻击克制破防，防御克制攻击，破防克制防御；成功防御获得能量，治疗消耗 2 能量。";
    internal const string RoundHeader = "第 {0} 回合";
    internal const string StatusName = "{0}";
    internal const string StatusHealth = "生命 {0}/{1}  {2}";
    internal const string StatusEnergy = "能量 {0}/3  {1}";
    internal const string StatusAppeal = "申诉机会：{0}";
    internal const string AppealAvailable = "可用";
    internal const string AppealUsed = "已使用";
    internal const string ActionPrompt = "秘密选择动作（1：攻击  2：防御  3：破防  4：治疗）：";
    internal const string HealEnergyMissing = "能量不足，治疗需要 2 点能量。";
    internal const string ActionAttack = "攻击";
    internal const string ActionGuard = "防御";
    internal const string ActionBreak = "破防";
    internal const string ActionHeal = "治疗";
    internal const string BothAction = "双方同时选择了{0}。";
    internal const string ActionReveal = "{0}选择了{1}；{2}选择了{3}。";
    internal const string DamageLine = "{0}受到 {1} 点伤害。";
    internal const string HealingLine = "{0}恢复 {1} 点生命。";
    internal const string GuardEnergy = "{0}成功防御并获得 1 点能量。";
    internal const string AiThinking = "电脑正在锁定本回合策略……";
    internal const string EventHeader = "命运事件";
    internal const string EventProposal = "{0}";
    internal const string EventEffect = "目标：{0}　效果：{1}";
    internal const string EffectRestore = "恢复 {0} 点生命";
    internal const string EffectLoss = "损失 {0} 点生命（事件不能致死）";
    internal const string EffectEnergy = "获得 {0} 点能量";
    internal const string HumanAppealPrompt = "事件对你不利。是否使用唯一一次申诉？（y/n）：";
    internal const string AppealArgumentPrompt = "请输入申诉理由（最多 200 字）：";
    internal const string ComputerAppeal = "{0}提出申诉：{1}";
    internal const string JudgeThinking = "独立裁判正在审理……";
    internal const string VerdictRevoke = "裁决：申诉成立，撤销事件。";
    internal const string VerdictUphold = "裁决：申诉驳回，维持事件。";
    internal const string VerdictReason = "理由：{0}";
    internal const string EventApplied = "事件已经生效。";
    internal const string EventCancelled = "事件已取消，战斗状态保持不变。";
    internal const string ResultHeader = "最终裁决";
    internal const string HumanWinner = "胜者：{0}";
    internal const string ComputerWinner = "胜者：{0}";
    internal const string Draw = "双方同时倒下，本局平局。";
    internal const string Farewell = "命运已经落笔，感谢参与本次审判。";
    internal const string LocalAppealArgument = "该事件在关键生命区间明显改变胜负，请依据公平预算撤销。";
    internal const string LocalEventRestore = "治愈之雨回应了坚持战斗的一方。";
    internal const string LocalEventLoss = "血月投下阴影，命运要求一方付出代价。";
    internal const string LocalEventEnergy = "能量喷泉涌现，战意得到补充。";
    internal const string LocalJudgeRevoke = "申诉引用了可验证的公平依据，事件撤销。";
    internal const string LocalJudgeUphold = "申诉缺少可验证的战斗证据，维持事件。";
}
