// <auto-generated />
namespace BattleGame.Cli;

// 此类型由 script/generate_l10n.sh 生成，请修改 assets_dev/l10n.csv 后重新生成。
internal static class GameText
{
    internal const string Title = "=== 回合制对战游戏 ===";
    internal const string NamePrompt = "请输入玩家名字：";
    internal const string NameEmpty = "名字不能为空，请重新输入。";
    internal const string InputEnded = "输入已结束，游戏退出。";
    internal const string ComputerName = "电脑";
    internal const string Versus = "{0} 对战 {1}";
    internal const string Rules = "双方生命值 {0}，攻击力 {1}，治疗可恢复 {2} 点生命。";
    internal const string Status = "状态：{0} {1}/{2} | {3} {4}/{5}";
    internal const string ActionPrompt = "请选择动作（1：攻击，2：治疗）：";
    internal const string InvalidAction = "无效选择，请输入 1 或 2。";
    internal const string Attack = "{0} 发起攻击，造成 {1} 点伤害。";
    internal const string Health = "{0} 当前生命：{1}/{2}";
    internal const string Heal = "{0} 恢复 {1} 点生命。";
    internal const string Winner = "胜者：{0}";
}
