#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"

python3 - "$project_root/assets_dev/challenges.csv" "$project_root/BattleGame.Online/LastChanceBank.g.cs" <<'PY'
import csv
import sys
from pathlib import Path

source = Path(sys.argv[1])
target = Path(sys.argv[2])

def literal(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')

with source.open(encoding="utf-8-sig", newline="") as stream:
    rows = list(csv.DictReader(stream))

lines = [
    "// <auto-generated />",
    "namespace BattleGame.Online;",
    "",
    "// 此类型由 script/generate_challenges.sh 生成，请修改 assets_dev/challenges.csv。",
    "public sealed class BuiltInLastChanceProvider : ILastChanceProvider",
    "{",
    "    private static readonly LastChanceDefinition[] Challenges =",
    "    {",
]

for row in rows:
    lines.extend([
        "        new LastChanceDefinition(",
        f'            "{literal(row["prompt"])}",',
        f'            "{literal(row["expected_text"])}",',
        f'            {int(row["required_count"])},',
        f'            TimeSpan.FromSeconds({int(row["duration_seconds"])}),',
        f'            {int(row["restore_health"])}),',
    ])

lines.extend([
    "    };",
    "    private int _nextIndex = -1;",
    "",
    "    public LastChanceDefinition Create()",
    "    {",
    "        int index = Interlocked.Increment(ref _nextIndex);",
    "        return Challenges[index % Challenges.Length];",
    "    }",
    "}",
    "",
])

target.write_text("\n".join(lines), encoding="utf-8")
PY
