#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"

# 生成文件不手工维护，保证控制台词条始终以 assets_dev CSV 为唯一来源。
python3 - "$project_root/assets_dev/l10n.csv" "$project_root/BattleGame.Cli/GameText.g.cs" <<'PY'
import csv
import re
import sys
from pathlib import Path

source = Path(sys.argv[1])
target = Path(sys.argv[2])

with source.open(encoding="utf-8-sig", newline="") as stream:
    rows = list(csv.DictReader(stream))

lines = [
    "// <auto-generated />",
    "namespace BattleGame.Cli;",
    "",
    "// 此类型由 script/generate_l10n.sh 生成，请修改 assets_dev/l10n.csv 后重新生成。",
    "internal static class GameText",
    "{",
]

for row in rows:
    key = row["key"]
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
        raise ValueError(f"非法词条键：{key}")
    value = row["zh_CN"].replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'    internal const string {key} = "{value}";')

lines.extend(["}", ""])
target.write_text("\n".join(lines), encoding="utf-8")
PY
