#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"

# 联网服务端也遵守词条单一来源，生成后发布包不再依赖开发目录中的 CSV。
python3 - "$project_root/assets_dev/fate_events.csv" "$project_root/BattleGame.Online/FateEventText.g.cs" <<'PY'
import csv
import re
import sys
from pathlib import Path

source, target = map(Path, sys.argv[1:])
with source.open(encoding="utf-8-sig", newline="") as stream:
    rows = list(csv.DictReader(stream))
lines = ["// <auto-generated />", "namespace BattleGame.Online;", "", "internal static class FateEventText", "{"]
for row in rows:
    key = row["key"]
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
        raise ValueError(key)
    value = row["zh_CN"].replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'    internal const string {key} = "{value}";')
lines.extend(["}", ""])
target.write_text("\n".join(lines), encoding="utf-8")
PY
