#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"

# 题面和解释也属于产品文案，统一从 CSV 生成，避免散落在服务端代码中。
python3 - "$project_root/assets_dev/questions.csv" "$project_root/BattleGame.Online/QuestionBank.g.cs" <<'PY'
import csv
import sys
from pathlib import Path

source = Path(sys.argv[1])
target = Path(sys.argv[2])

def literal(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')

with source.open(encoding="utf-8-sig", newline="") as stream:
    rows = list(csv.DictReader(stream))

lines = [
    "// <auto-generated />",
    "using System.Security.Cryptography;",
    "",
    "namespace BattleGame.Online;",
    "",
    "// 此类型由 script/generate_questions.sh 生成，请修改 assets_dev/questions.csv。",
    "public sealed class BuiltInQuestionProvider : IQuestionProvider",
    "{",
    "    private static readonly KnowledgeQuestion[] Questions =",
    "    {",
]

for row in rows:
    options = ", ".join(f'"{literal(row[key])}"' for key in ("option_a", "option_b", "option_c", "option_d"))
    lines.extend([
        "        new KnowledgeQuestion(",
        f'            "{literal(row["id"])}",',
        f'            QuestionCategory.{row["category"]},',
        f'            "{literal(row["prompt"])}",',
        f"            new[] {{ {options} }},",
        f'            {int(row["correct_index"])},',
        f'            "{literal(row["explanation"])}"),',
    ])

lines.extend([
    "    };",
    "",
    "    public KnowledgeQuestion GetNext(int roundNumber)",
    "    {",
    "        return Questions[RandomNumberGenerator.GetInt32(Questions.Length)];",
    "    }",
    "}",
    "",
])

target.write_text("\n".join(lines), encoding="utf-8")
PY
