#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"

python3 - "$project_root/assets_dev/tags.csv" "$project_root/BattleGame.Online/TagCatalog.g.cs" <<'PY'
import csv
import sys
from pathlib import Path

source = Path(sys.argv[1])
target = Path(sys.argv[2])

def literal(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')

with source.open(encoding="utf-8-sig", newline="") as stream:
    rows = list(csv.DictReader(stream))

lines = [
    "// <auto-generated />",
    "namespace BattleGame.Online;",
    "",
    "// 此类型由 script/generate_tags.sh 生成，请修改 assets_dev/tags.csv。",
    "public sealed class BuiltInTagCatalog : ITagCatalog",
    "{",
    "    private static readonly TagDefinition[] Tags =",
    "    {",
]

for row in rows:
    hours = int(row["lifetime_hours"])
    lifetime = "null" if hours == 0 else f"TimeSpan.FromHours({hours})"
    lines.append(
        f'        new TagDefinition("{literal(row["code"])}", '
        f'"{literal(row["display_name"])}", {lifetime}),')

lines.extend([
    "    };",
    "",
    "    public IReadOnlyList<TagDefinition> GetAll() => Tags;",
    "}",
    "",
])

target.write_text("\n".join(lines), encoding="utf-8")
PY
