// <auto-generated />
namespace BattleGame.Online;

internal static class FateEventText
{
    internal const string RestoreHost = "命运补给落在房主阵营，恢复生命。";
    internal const string LossGuest = "法庭风暴袭向挑战者，扣除生命。";
    internal const string EnergyGuest = "挑战者捕捉到能量裂隙，获得能量。";
    internal const string LossHost = "命运税单落在房主身上，扣除生命。";
    internal const string JudgeRevoke = "申诉指出了可验证的局势失衡，本次事件撤销。";
    internal const string JudgeUphold = "申诉没有证明事件违反受控规则，本次事件维持。";
}
