// <auto-generated />
namespace BattleGame.Online;

// 此类型由 script/generate_challenges.sh 生成，请修改 assets_dev/challenges.csv。
public sealed class BuiltInLastChanceProvider : ILastChanceProvider
{
    private static readonly LastChanceDefinition[] Challenges =
    {
        new LastChanceDefinition(
            "30 秒内正确输入 25 次“加油”",
            "加油",
            25,
            TimeSpan.FromSeconds(30),
            5),
        new LastChanceDefinition(
            "20 秒内把数字“4927”倒序输入",
            "7294",
            1,
            TimeSpan.FromSeconds(20),
            5),
        new LastChanceDefinition(
            "20 秒内回答：2、4、8、16 的下一项是什么？",
            "32",
            1,
            TimeSpan.FromSeconds(20),
            5),
    };
    private int _nextIndex = -1;

    public LastChanceDefinition Create()
    {
        int index = Interlocked.Increment(ref _nextIndex);
        return Challenges[index % Challenges.Length];
    }
}
