// <auto-generated />
using System.Security.Cryptography;

namespace BattleGame.Online;

// 此类型由 script/generate_questions.sh 生成，请修改 assets_dev/questions.csv。
public sealed class BuiltInQuestionProvider : IQuestionProvider
{
    private static readonly KnowledgeQuestion[] Questions =
    {
        new KnowledgeQuestion(
            "math_linear_1",
            QuestionCategory.Math,
            "3x + 7 = 22，x 等于多少？",
            new[] { "3", "5", "7", "9" },
            1,
            "代入 x=5 可得 3×5+7=22。"),
        new KnowledgeQuestion(
            "math_fast_1",
            QuestionCategory.Math,
            "48 ÷ 6 + 7 等于多少？",
            new[] { "13", "14", "15", "16" },
            2,
            "先算除法 48÷6=8，再加 7 得 15。"),
        new KnowledgeQuestion(
            "language_idiom_1",
            QuestionCategory.Language,
            "哪个成语表示把错误彻底改正？",
            new[] { "一成不变", "改过自新", "守株待兔", "刻舟求剑" },
            1,
            "改过自新指改正错误并重新做人。"),
        new KnowledgeQuestion(
            "english_word_1",
            QuestionCategory.English,
            "哪个英文单词表示“勇气”？",
            new[] { "courage", "cloud", "court", "culture" },
            0,
            "courage 的含义是勇气。"),
        new KnowledgeQuestion(
            "history_tang_1",
            QuestionCategory.History,
            "唐朝的建立者是谁？",
            new[] { "李世民", "李渊", "武则天", "朱元璋" },
            1,
            "李渊于 618 年建立唐朝。"),
        new KnowledgeQuestion(
            "geography_ocean_1",
            QuestionCategory.Geography,
            "世界上面积最大的大洋是？",
            new[] { "大西洋", "印度洋", "北冰洋", "太平洋" },
            3,
            "太平洋是世界上面积最大的大洋。"),
        new KnowledgeQuestion(
            "biology_cell_1",
            QuestionCategory.Biology,
            "植物细胞进行光合作用的主要场所是？",
            new[] { "细胞核", "线粒体", "叶绿体", "液泡" },
            2,
            "叶绿体含有叶绿素，是光合作用的主要场所。"),
        new KnowledgeQuestion(
            "common_leap_1",
            QuestionCategory.CommonSense,
            "通常情况下闰年有多少天？",
            new[] { "365", "366", "364", "367" },
            1,
            "闰年二月有 29 天，全年共 366 天。"),
        new KnowledgeQuestion(
            "logic_sequence_1",
            QuestionCategory.Logic,
            "数列 2、4、8、16 的下一项是？",
            new[] { "18", "24", "30", "32" },
            3,
            "每一项都是前一项的 2 倍。"),
        new KnowledgeQuestion(
            "logic_relation_1",
            QuestionCategory.Logic,
            "所有法官都读规则，小林是法官，可以推出什么？",
            new[] { "小林读规则", "小林写规则", "读规则的人都是法官", "无法判断小林是否读规则" },
            0,
            "由全称条件和小林属于法官可推出小林读规则。"),
        new KnowledgeQuestion(
            "brain_water_1",
            QuestionCategory.BrainTeaser,
            "什么东西越洗越脏？",
            new[] { "毛巾", "水", "衣服", "肥皂" },
            1,
            "水清洗其他物品后会变脏。"),
        new KnowledgeQuestion(
            "brain_map_1",
            QuestionCategory.BrainTeaser,
            "什么东西有城市却没有房屋，有河流却没有水？",
            new[] { "地图", "梦境", "书本", "镜子" },
            0,
            "地图会标记城市与河流，但不包含真实房屋和水。"),
    };

    public KnowledgeQuestion GetNext(int roundNumber)
    {
        return Questions[RandomNumberGenerator.GetInt32(Questions.Length)];
    }
}
