// <auto-generated />
namespace BattleGame.Online;

// 此类型由 script/generate_tags.sh 生成，请修改 assets_dev/tags.csv。
public sealed class BuiltInTagCatalog : ITagCatalog
{
    private static readonly TagDefinition[] Tags =
    {
        new TagDefinition("never_give_up", "永不言弃", TimeSpan.FromHours(24)),
        new TagDefinition("defense_master", "防守大师", TimeSpan.FromHours(24)),
        new TagDefinition("break_specialist", "破防专业户", TimeSpan.FromHours(24)),
        new TagDefinition("knowledge_challenger", "全科挑战者", TimeSpan.FromHours(24)),
        new TagDefinition("close_call", "差一题就赢", TimeSpan.FromHours(24)),
        new TagDefinition("healing_fan", "治疗爱好者", TimeSpan.FromHours(24)),
        new TagDefinition("fast_thinker", "极速思考者", TimeSpan.FromHours(24)),
        new TagDefinition("fate_survivor", "绝境幸存者", null),
    };

    public IReadOnlyList<TagDefinition> GetAll() => Tags;
}
