<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BattleGame.Online\BattleGame.Online.csproj" />
    <ProjectReference Include="..\BattleGame.Persistence\BattleGame.Persistence.csproj" />
  </ItemGroup>

</Project>
